name: Publicar Pagina a Surge.sh

# Triggers (activadores) del flujo de trabajo
on:
  push:
    branches:
      - main

# Definición del trabajo
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Configura Node.js  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala Surge
        run: npm install --global surge

      - name: Publicar página en Surge
        run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_API_KEY }}
